package javaapplication52;

// ======= DO NOT EDIT THIS FILE =============
//This stack is used for Graph depth-first traversal
//-----------------------------------------------------------------------
import java.util.*;

public class Stack {

    LinkedList<Node> t;

    Stack() {
        t = new LinkedList<Node>();
    }

    boolean isEmpty() {
        return (t.isEmpty());
    }

    void clear() {
        t.clear();
    }

    void push(Node x) {
        t.addLast(x);
    }

    Node pop() {
        if (isEmpty()) {
            return (null);
        }
        return (t.removeLast());
    }

    Node top() {
        if (isEmpty()) {
            return (null);
        }
        return (t.getLast());
    }
}
